name: CI ISO-810 TEST ON HEROKU

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches: 
      - master
    types: [closed]
    
jobs:
  build_icolors:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'iso810' }}
      run: |
        pwd
        ls
        cd ./
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
